### PR TITLE
Bump to Hazelcast-kubernetes-bootstrapper 3.9.2

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
I guess now we need you to build 3.9.2 on Quay :-)

**Comment by pires** [comment]
No need. If you create a tag `3.9.2`, quay will build it automatically ;)

**Comment by oscerd** [comment]
I'm doing it :-)

**Comment by oscerd** [comment]
Done, waiting for the build :-)

**Pull request merged**
